apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: run-mediawiki
description: main application pipeline
serialPipeline:
  stages:
  - targetId: run-qsprod
    profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsprod
description: Cloud Run production service
run:
  location: projects/wiki-imabernal/locations/southamerica-east1